"""Spatiotemporal and true-video experiment register."""

SPATIOTEMPORAL_VIDEO_EXPERIMENTS = {
    "VID-ST-01": {
        "experiment_no": "VID-ST-01",
        "category": "spatiotemporal",
        "family": "Xception Hybrid",
        "model_name": "xception71",
        "params_note": "~84M",
        "mode": "sequence",
        "seq_len": 12,
        "batch_size": 8,
        "role": "Baseline",
        "what_it_tests": "Lightweight hybrid behavior with an older deepfake backbone.",
        "strong_point": "Efficient.",
    },
    "VID-ST-02": {
        "experiment_no": "VID-ST-02",
        "category": "spatiotemporal",
        "family": "ConvNeXt Hybrid",
        "model_name": "convnext_base",
        "params_note": "~88M",
        "mode": "sequence",
        "seq_len": 12,
        "batch_size": 8,
        "role": "Baseline",
        "what_it_tests": "Spatial plus temporal fusion with a balanced CNN backbone.",
        "strong_point": "Balanced.",
    },
    "VID-ST-03": {
        "experiment_no": "VID-ST-03",
        "category": "spatiotemporal",
        "family": "ConvNeXt Hybrid",
        "model_name": "convnext_large",
        "params_note": "~198M",
        "mode": "sequence",
        "seq_len": 12,
        "batch_size": 4,
        "role": "Scaling",
        "what_it_tests": "CNN hybrid scaling with stronger per-frame features.",
        "strong_point": "Stronger fusion.",
    },
    "VID-ST-04": {
        "experiment_no": "VID-ST-04",
        "category": "spatiotemporal",
        "family": "Swin Hybrid",
        "model_name": "swin_base_patch4_window7_224",
        "params_note": "~88M",
        "mode": "sequence",
        "seq_len": 12,
        "batch_size": 8,
        "role": "Probe",
        "what_it_tests": "Structured spatiotemporal fusion with hierarchical attention.",
        "strong_point": "Strong balance.",
    },
    "VID-ST-05": {
        "experiment_no": "VID-ST-05",
        "category": "spatiotemporal",
        "family": "MaxViT Hybrid",
        "model_name": "maxvit_base_tf_224.in1k",
        "params_note": "~119M",
        "mode": "sequence",
        "seq_len": 12,
        "batch_size": 4,
        "role": "Advanced",
        "what_it_tests": "Local plus global spatiotemporal fusion.",
        "strong_point": "Best hybrid inductive bias.",
    },
    "VID-ST-06": {
        "experiment_no": "VID-ST-06",
        "category": "spatiotemporal",
        "family": "MaxViT Hybrid",
        "model_name": "maxvit_large_tf_224.in1k",
        "params_note": "~212M",
        "mode": "sequence",
        "seq_len": 12,
        "batch_size": 2,
        "role": "Scaling",
        "what_it_tests": "Hybrid scaling ceiling for richer spatiotemporal fusion.",
        "strong_point": "High ceiling.",
    },
    "VID-ST-07": {
        "experiment_no": "VID-ST-07",
        "category": "spatiotemporal",
        "family": "ConvNeXt ConvLSTM",
        "model_name": "convnext_large",
        "params_note": "~198M + ConvLSTM map head",
        "mode": "sequence",
        "seq_len": 8,
        "batch_size": 2,
        "temporal_head": "convlstm",
        "temporal_hidden_dim": 256,
        "temporal_layers": 1,
        "temporal_dropout": 0.2,
        "role": "Spatiotemporal recurrent probe",
        "what_it_tests": "Whether preserving ConvNeXt feature maps during recurrent fusion improves over vector temporal heads.",
        "strong_point": "Joint spatial-map and temporal-state modeling.",
    },
    "VID-ST-08": {
        "experiment_no": "VID-ST-08",
        "category": "spatiotemporal",
        "family": "ConvNeXt Hybrid Transformer",
        "model_name": "convnext_large",
        "params_note": "~198M + temporal transformer head",
        "mode": "sequence",
        "seq_len": 12,
        "batch_size": 4,
        "temporal_head": "transformer",
        "temporal_hidden_dim": 512,
        "temporal_layers": 1,
        "temporal_dropout": 0.2,
        "role": "Hybrid attention probe",
        "what_it_tests": "Whether stronger ConvNeXt features plus temporal attention improve the hybrid branch.",
        "strong_point": "Temporal attention over high-capacity frame features.",
    },
    "VID-ST-09": {
        "experiment_no": "VID-ST-09",
        "category": "spatiotemporal",
        "family": "ConvNeXt Hybrid TCN",
        "model_name": "convnext_large",
        "params_note": "~198M + temporal convolution head",
        "mode": "sequence",
        "seq_len": 12,
        "batch_size": 4,
        "temporal_head": "tcn",
        "temporal_hidden_dim": 512,
        "temporal_layers": 1,
        "temporal_dropout": 0.2,
        "role": "Hybrid temporal-conv probe",
        "what_it_tests": "Whether a temporal convolution head improves the spatiotemporal branch without recurrent state.",
        "strong_point": "Efficient temporal fusion.",
    },
}
