"""Spatial single-frame video experiment register."""

SPATIAL_VIDEO_EXPERIMENTS = {
    "VID-SPA-01": {
        "experiment_no": "VID-SPA-01",
        "category": "spatial",
        "family": "Xception",
        "model_name": "xception71",
        "params_note": "~84M",
        "mode": "single",
        "seq_len": 1,
        "batch_size": 16,
        "role": "Baseline",
        "what_it_tests": "Legacy deepfake CNN behavior on raw-video frame cues.",
        "strong_point": "Efficient and proven.",
    },
    "VID-SPA-02": {
        "experiment_no": "VID-SPA-02",
        "category": "spatial",
        "family": "ConvNeXt",
        "model_name": "convnext_base",
        "params_note": "~88M",
        "mode": "single",
        "seq_len": 1,
        "batch_size": 16,
        "role": "Baseline",
        "what_it_tests": "Modern CNN representation on raw-video spatial cues.",
        "strong_point": "Stable and strong default.",
    },
    "VID-SPA-03": {
        "experiment_no": "VID-SPA-03",
        "category": "spatial",
        "family": "ConvNeXt",
        "model_name": "convnext_large",
        "params_note": "~198M",
        "mode": "single",
        "seq_len": 1,
        "batch_size": 8,
        "role": "Scaling",
        "what_it_tests": "CNN capacity scaling on frame-level forensic cues.",
        "strong_point": "Richer features.",
    },
    "VID-SPA-04": {
        "experiment_no": "VID-SPA-04",
        "category": "spatial",
        "family": "ConvNeXtV2",
        "model_name": "convnextv2_base.fcmae_ft_in22k_in1k",
        "params_note": "~89M",
        "mode": "single",
        "seq_len": 1,
        "batch_size": 16,
        "role": "Baseline",
        "what_it_tests": "Whether ConvNeXtV2 training improvements help raw-video spatial learning.",
        "strong_point": "Better convergence.",
    },
    "VID-SPA-05": {
        "experiment_no": "VID-SPA-05",
        "category": "spatial",
        "family": "ConvNeXtV2",
        "model_name": "convnextv2_large.fcmae_ft_in22k_in1k",
        "params_note": "~198M",
        "mode": "single",
        "seq_len": 1,
        "batch_size": 8,
        "role": "Scaling",
        "what_it_tests": "ConvNeXtV2 scaling with GRN-era training behavior.",
        "strong_point": "Strong CNN ceiling.",
    },
    "VID-SPA-06": {
        "experiment_no": "VID-SPA-06",
        "category": "spatial",
        "family": "Swin",
        "model_name": "swin_base_patch4_window7_224",
        "params_note": "~88M",
        "mode": "single",
        "seq_len": 1,
        "batch_size": 16,
        "role": "Probe",
        "what_it_tests": "Local-window hierarchical attention on raw-video frame cues.",
        "strong_point": "Best balanced transformer.",
    },
    "VID-SPA-07": {
        "experiment_no": "VID-SPA-07",
        "category": "spatial",
        "family": "Swin",
        "model_name": "swin_large_patch4_window7_224",
        "params_note": "~197M",
        "mode": "single",
        "seq_len": 1,
        "batch_size": 8,
        "role": "Scaling",
        "what_it_tests": "Transformer scaling for hierarchical windowed attention.",
        "strong_point": "Strong high-capacity.",
    },
    "VID-SPA-08": {
        "experiment_no": "VID-SPA-08",
        "category": "spatial",
        "family": "ViT",
        "model_name": "vit_base_patch16_224",
        "params_note": "~86M",
        "mode": "single",
        "seq_len": 1,
        "batch_size": 16,
        "role": "Probe",
        "what_it_tests": "Global attention without strong convolutional inductive bias.",
        "strong_point": "No inductive bias.",
    },
    "VID-SPA-09": {
        "experiment_no": "VID-SPA-09",
        "category": "spatial",
        "family": "EVA",
        "model_name": "eva02_base_patch14_224.mim_in22k_ft_in22k_in1k",
        "params_note": "~86-100M",
        "mode": "single",
        "seq_len": 1,
        "batch_size": 12,
        "role": "Probe",
        "what_it_tests": "Whether stronger pretrained ViT initialization beats vanilla ViT.",
        "strong_point": "Better than vanilla ViT.",
    },
    "VID-SPA-10": {
        "experiment_no": "VID-SPA-10",
        "category": "spatial",
        "family": "MaxViT",
        "model_name": "maxvit_base_tf_224.in1k",
        "params_note": "~119M",
        "mode": "single",
        "seq_len": 1,
        "batch_size": 8,
        "role": "Advanced",
        "what_it_tests": "Local plus global hybrid attention for frame-level deepfake cues.",
        "strong_point": "Strong inductive mix.",
    },
    "VID-SPA-11": {
        "experiment_no": "VID-SPA-11",
        "category": "spatial",
        "family": "MaxViT",
        "model_name": "maxvit_large_tf_224.in1k",
        "params_note": "~212M",
        "mode": "single",
        "seq_len": 1,
        "batch_size": 4,
        "role": "Scaling",
        "what_it_tests": "Hybrid attention scaling on raw-video spatial learning.",
        "strong_point": "High ceiling.",
    },
}
