"""Unified dataset loading utilities for image and video deepfake experiments.

This module is the active data entrypoint used by training, evaluation, and data
inspection scripts.

Primary training path:
- image datasets feed image-only models
- raw video datasets feed video-only models
  - `mode="single"` acts as the spatial baseline on video data
  - `mode="sequence"` acts as the spatial+temporal path

Optional support remains for extracted frame folders, but frame materialization
is auxiliary and is not required for the default raw-video workflow.
"""

import os
import random
import cv2
import numpy as np
import warnings
from pathlib import Path
from collections import Counter, defaultdict

# 🔥 Suppress FFmpeg/OpenCV noise
os.environ["OPENCV_LOG_LEVEL"] = "FATAL"
os.environ["FFMPEG_LOG_LEVEL"] = "quiet"

try:
    import decord
    from decord import VideoReader, cpu
    HAS_DECORD = True
except ImportError:
    HAS_DECORD = False

from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms

Image.MAX_IMAGE_PIXELS = None
warnings.filterwarnings("ignore", category=Image.DecompressionBombWarning)

# =========================
# CONFIG
# =========================

IMAGE_EXTS = [".jpg", ".jpeg", ".png", ".webp", ".bmp"]
VIDEO_EXTS = [".mp4", ".avi", ".mov", ".mkv"]
NUM_WORKERS = 8
DEFAULT_IMAGE_VAL_RATIO = 0.15
DEFAULT_VIDEO_TRAIN_RATIO = 0.7
DEFAULT_VIDEO_VAL_RATIO = 0.1
DEFAULT_SEQUENCE_LEN = 8
DEFAULT_PREFETCH_FACTOR = 2

DATASET_CONFIG = {
    "images": {
        "ai-generated-images-vs-real-images": {"type": "image", "structure": "split_class", "classes": {"fake": 0, "real": 1}},
        "cifake": {"type": "image", "structure": "split_class", "classes": {"FAKE": 0, "REAL": 1}},
        # Optional derived dataset generated by datasets/extract_ff_frames.py
        "faceforensics_frames": {"type": "image", "structure": "split_class", "classes": {"fake": 0, "real": 1}},
    },
    "videos": {
        "celeb-df-v2": {
            "type": "video", "structure": "flat_class", 
            "classes": {"Celeb-real": 1, "YouTube-real": 1, "Celeb-fake": 0}
        },
        "faceforensics++": {
            "type": "video", "structure": "deep_nested",
            "rules": {"fake_paths": ["fake"], "real_paths": ["real"]}
        },
        "real-ai-videos": {
            "type": "video", "structure": "flat_class", 
            "classes": {"ai": 0, "fake": 0, "real": 1}
        }
    }
}

FRAME_DATASET_SOURCES = {
    "preprocessed_frames": {"root": Path("datasets/preprocessed_frames"), "layout": "video_mirror"},
    "video-frames": {"root": Path("video-frames"), "layout": "label_dataset_video"},
}


def build_loader_kwargs(batch_size, shuffle=False, drop_last=False):
    """Centralize DataLoader runtime settings for raw-video training."""
    kwargs = {
        "batch_size": batch_size,
        "shuffle": shuffle,
        "num_workers": NUM_WORKERS,
        "pin_memory": True,
        "drop_last": drop_last,
    }
    if NUM_WORKERS > 0:
        kwargs["persistent_workers"] = True
        kwargs["prefetch_factor"] = DEFAULT_PREFETCH_FACTOR
    return kwargs

# =========================
# DATASET
# =========================

class DeepFakeDataset(Dataset):
    def __init__(self, samples, transform=None, mode="single", seq_len=8, clip_sampling="random"):
        self.samples = samples
        self.transform = transform
        self.mode = mode
        self.seq_len = seq_len
        self.clip_sampling = clip_sampling

    def __len__(self):
        return len(self.samples)

    def _read_frame(self, cap, frame_id):
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_id)
        ret, frame = cap.read()
        return Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)) if ret else None

    def _read_frame_dir_image(self, frame_files, index):
        if not frame_files:
            return Image.new("RGB", (224, 224))
        clamped = max(0, min(index, len(frame_files) - 1))
        return Image.open(frame_files[clamped]).convert("RGB")

    def _single_index(self, total_frames):
        if total_frames <= 0:
            return 0
        if self.clip_sampling == "center":
            return total_frames // 2
        return random.randint(0, total_frames - 1)

    def _list_frame_files(self, frame_dir):
        frame_dir = Path(frame_dir)
        return sorted(
            str(item)
            for item in frame_dir.iterdir()
            if item.is_file() and item.suffix.lower() in IMAGE_EXTS
        )

    def _contiguous_indices(self, total_frames):
        if total_frames <= 0:
            return [0] * self.seq_len
        if total_frames <= self.seq_len:
            return list(range(total_frames)) + [max(total_frames - 1, 0)] * (self.seq_len - total_frames)
        if self.clip_sampling == "center":
            start = max((total_frames - self.seq_len) // 2, 0)
        else:
            start = random.randint(0, total_frames - self.seq_len)
        return list(range(start, start + self.seq_len))

    def __getitem__(self, idx):
        path, label, dtype = self.samples[idx]
        try:
            if self.mode == "single":
                if dtype == "image":
                    img = Image.open(path).convert("RGB")
                elif dtype == "video":
                    if HAS_DECORD:
                        vr = VideoReader(path, ctx=cpu(0))
                        img = Image.fromarray(vr[self._single_index(len(vr))].asnumpy())
                    else:
                        cap = cv2.VideoCapture(path)
                        img = self._read_frame(cap, self._single_index(int(cap.get(cv2.CAP_PROP_FRAME_COUNT))))
                        cap.release()
                elif dtype == "frame":
                    frame_files = self._list_frame_files(path)
                    img = self._read_frame_dir_image(frame_files, self._single_index(len(frame_files)))
                if self.transform: img = self.transform(img)
                return img, label

            elif self.mode == "sequence":
                if dtype == "frame":
                    frame_files = self._list_frame_files(path)
                    indices = self._contiguous_indices(len(frame_files))
                    frames = []
                    for i in indices:
                        img = self._read_frame_dir_image(frame_files, i)
                        if self.transform:
                            img = self.transform(img)
                        frames.append(img)
                    return torch.stack(frames), label
                if HAS_DECORD:
                    vr = VideoReader(path, ctx=cpu(0))
                    indices = self._contiguous_indices(len(vr))
                    frames = [Image.fromarray(f.asnumpy()) for f in vr.get_batch(indices)]
                    if self.transform: frames = [self.transform(f) for f in frames]
                    return torch.stack(frames), label
                else:
                    cap = cv2.VideoCapture(path)
                    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
                    indices = self._contiguous_indices(total_frames)
                    frames = []
                    for i in indices:
                        img = self._read_frame(cap, i)
                        if img is None: img = frames[-1] if frames else Image.new('RGB', (224, 224))
                        if self.transform: img = self.transform(img)
                        frames.append(img)
                    cap.release()
                    return torch.stack(frames), label
            raise ValueError(f"Unsupported mode: {self.mode}")
        except Exception:
            shape = (3, 224, 224) if self.mode == "single" else (self.seq_len, 3, 224, 224)
            return torch.zeros(shape), label

# =========================
# BUILDER
# =========================

class _LegacyDatasetBuilder:
    def __init__(self, root="datasets"):
        self.root = Path(root)
        self.samples = []

    def _is_image_file(self, path):
        return path.is_file() and path.suffix.lower() in IMAGE_EXTS

    def _is_video_file(self, path):
        return path.is_file() and path.suffix.lower() in VIDEO_EXTS

    def _is_frame_dir(self, path):
        if not path.is_dir():
            return False
        return any(item.is_file() and item.suffix.lower() in IMAGE_EXTS for item in path.iterdir())

    def _infer_label_from_path(self, path):
        parts = [part.lower() for part in Path(path).parts]
        if "real" in parts or "youtube-real" in parts or "celeb-real" in parts:
            return 1
        if "fake" in parts or "celeb-fake" in parts or "ai" in parts:
            return 0
        path_str = str(path).lower().replace("\\", "/")
        if "/real/" in path_str:
            return 1
        if "/fake/" in path_str or "/ai/" in path_str:
            return 0
        return None

    def get_identity(self, path):
        """Extracts Person ID for subject-independent splitting."""
        name = Path(path).name.lower()
        # CelebDF: id0_id1_0000.mp4 -> id0
        if name.startswith("id"):
            return name.split("_")[0]
        # FF++: 000_001.mp4 -> 000
        if "_" in name and name[:3].isdigit():
            return name.split("_")[0]
        # Fallback to full path (treat as unique identity)
        return path

    def scan_images(self):
        root = self.root / "images"
        if not root.exists(): return
        for ds, cfg in DATASET_CONFIG["images"].items():
            ds_path = root / ds
            if not ds_path.exists(): continue
            # Discover split folders from disk instead of assuming only train/test.
            for split_dir in sorted([p for p in ds_path.iterdir() if p.is_dir()]):
                split = split_dir.name
                if split.startswith("."):
                    continue
                for cls, label in cfg["classes"].items():
                    cls_dir = split_dir / cls
                    if not cls_dir.exists(): continue
                    for img in cls_dir.rglob("*"):
                        if not self._is_image_file(img):
                            continue
                        self.samples.append((str(img), label, "image"))

    def scan_videos(self):
        root = self.root / "videos"
        if not root.exists(): return
        for ds, cfg in DATASET_CONFIG["videos"].items():
            ds_path = root / ds
            if not ds_path.exists(): continue
            if cfg["structure"] == "flat_class":
                for cls, label in cfg["classes"].items():
                    cls_dir = ds_path / cls
                    if cls_dir.exists():
                        for v in cls_dir.rglob("*"):
                            if self._is_video_file(v):
                                self.samples.append((str(v), label, "video"))
            elif cfg["structure"] == "deep_nested":
                for p in cfg["rules"]["fake_paths"]:
                    d = ds_path / p
                    if d.exists():
                        for v in d.rglob("*"):
                            if self._is_video_file(v):
                                self.samples.append((str(v), 0, "video"))
                for p in cfg["rules"]["real_paths"]:
                    d = ds_path / p
                    if d.exists():
                        for v in d.rglob("*"):
                            if self._is_video_file(v):
                                self.samples.append((str(v), 1, "video"))

    def scan_frames(self):
        for frame_source in FRAME_DATASET_SOURCES.values():
            root = frame_source["root"]
            if not root.exists():
                continue

            for frame_dir in root.rglob("*"):
                if not self._is_frame_dir(frame_dir):
                    continue

                label = self._infer_label_from_path(frame_dir)
                if label is None:
                    continue

                self.samples.append((str(frame_dir), label, "frame"))

    def build(self):
        print("\n🔍 Scanning datasets...")
        self.samples = []
        self.scan_images(); self.scan_videos(); self.scan_frames()
        print(f"Total samples: {len(self.samples)}")

    def split_samples(self, samples, train_ratio=0.7, val_ratio=0.2):
        """Subject-Independent Split: Group by Person ID."""
        groups = {}
        for s in samples:
            identity = self.get_identity(s[0])
            if identity not in groups: groups[identity] = []
            groups[identity].append(s)
        
        identities = list(groups.keys())
        random.shuffle(identities)
        
        n = len(identities)
        t_idx, v_idx = int(n * train_ratio), int(n * (train_ratio + val_ratio))
        
        train = [s for i in identities[:t_idx] for s in groups[i]]
        val = [s for i in identities[t_idx:v_idx] for s in groups[i]]
        test = [s for i in identities[v_idx:] for s in groups[i]]
        
        print(f"👥 Unique Identities found: {len(identities)}")
        return train, val, test

    def get_loaders(self, batch_size=32, mode="single", seq_len=8, dtype=None, balanced=True):
        self.build()
        filtered = [s for s in self.samples if s[2] == dtype] if dtype else self.samples
        train, val, test = self.split_samples(filtered)

        tf_train = transforms.Compose([
            transforms.RandomResizedCrop(224, scale=(0.9, 1.0)),
            transforms.RandomHorizontalFlip(),
            transforms.ColorJitter(0.2, 0.2, 0.2),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])
        tf_val = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])

        if balanced:
            counts = Counter([s[1] for s in train])
            max_c = max(counts.values())
            balanced_train = []
            for label in counts.keys():
                cls_s = [s for s in train if s[1] == label]
                mult = max_c // len(cls_s)
                balanced_train.extend(cls_s * mult)
                balanced_train.extend(random.sample(cls_s, max_c - len(cls_s)*mult))
            train = balanced_train

        print(f"\n📊 SPLIT: Train={len(train)}, Val={len(val)}, Test={len(test)}")
        
        return (
            DataLoader(DeepFakeDataset(train, tf_train, mode, seq_len), batch_size=batch_size, shuffle=True, num_workers=NUM_WORKERS, pin_memory=True, drop_last=True),
            DataLoader(DeepFakeDataset(val, tf_val, mode, seq_len), batch_size=batch_size, num_workers=NUM_WORKERS, pin_memory=True),
            DataLoader(DeepFakeDataset(test, tf_val, mode, seq_len), batch_size=batch_size, num_workers=NUM_WORKERS, pin_memory=True)
        )


class DatasetBuilder(_LegacyDatasetBuilder):
    """Protocol-aware dataset builder.

    Defaults:
    - dtype='image' -> protocol='image_only'
    - dtype='video' -> protocol='video_only'
    - dtype='frame' -> protocol='frame_only'
    - dtype=None -> protocol='combined_aux'

    Research interpretation:
    - image_only -> image-model path
    - video_only + single -> spatial baseline on videos
    - video_only + sequence -> spatial+temporal training path
    - frame_only -> auxiliary derived-frame experiments
    """

    def __init__(self, root="datasets", seed=42):
        super().__init__(root=root)
        self.seed = seed
        self.records = []

    def _rng(self):
        return random.Random(self.seed)

    def _record_to_sample(self, record):
        return (record["path"], record["label"], record["dtype"])

    def scan_images(self):
        root = self.root / "images"
        if not root.exists():
            return

        for dataset_name, cfg in DATASET_CONFIG["images"].items():
            ds_path = root / dataset_name
            if not ds_path.exists():
                continue

            for split_dir in sorted([p for p in ds_path.iterdir() if p.is_dir()]):
                split_name = split_dir.name.lower()
                if split_name.startswith("."):
                    continue

                for class_name, label in cfg["classes"].items():
                    cls_dir = split_dir / class_name
                    if not cls_dir.exists():
                        continue

                    for img_path in cls_dir.rglob("*"):
                        if not self._is_image_file(img_path):
                            continue

                        self.records.append(
                            {
                                "path": str(img_path),
                                "label": label,
                                "dtype": "image",
                                "dataset": dataset_name,
                                "source_split": split_name,
                                "identity": str(img_path),
                            }
                        )
                        self.samples.append((str(img_path), label, "image"))

    def scan_videos(self):
        root = self.root / "videos"
        if not root.exists():
            return

        for dataset_name, cfg in DATASET_CONFIG["videos"].items():
            ds_path = root / dataset_name
            if not ds_path.exists():
                continue

            if cfg["structure"] == "flat_class":
                for class_name, label in cfg["classes"].items():
                    cls_dir = ds_path / class_name
                    if not cls_dir.exists():
                        continue

                    for video_path in cls_dir.rglob("*"):
                        if not self._is_video_file(video_path):
                            continue

                        record = {
                            "path": str(video_path),
                            "label": label,
                            "dtype": "video",
                            "dataset": dataset_name,
                            "source_split": None,
                            "identity": self.get_identity(str(video_path)),
                        }
                        self.records.append(record)
                        self.samples.append((record["path"], record["label"], record["dtype"]))

            elif cfg["structure"] == "deep_nested":
                for rel_path in cfg["rules"]["fake_paths"]:
                    nested_dir = ds_path / rel_path
                    if not nested_dir.exists():
                        continue

                    for video_path in nested_dir.rglob("*"):
                        if not self._is_video_file(video_path):
                            continue

                        record = {
                            "path": str(video_path),
                            "label": 0,
                            "dtype": "video",
                            "dataset": dataset_name,
                            "source_split": None,
                            "identity": self.get_identity(str(video_path)),
                        }
                        self.records.append(record)
                        self.samples.append((record["path"], record["label"], record["dtype"]))

                for rel_path in cfg["rules"]["real_paths"]:
                    nested_dir = ds_path / rel_path
                    if not nested_dir.exists():
                        continue

                    for video_path in nested_dir.rglob("*"):
                        if not self._is_video_file(video_path):
                            continue

                        record = {
                            "path": str(video_path),
                            "label": 1,
                            "dtype": "video",
                            "dataset": dataset_name,
                            "source_split": None,
                            "identity": self.get_identity(str(video_path)),
                        }
                        self.records.append(record)
                        self.samples.append((record["path"], record["label"], record["dtype"]))

    def _frame_record(self, frame_dir, dataset_name, label, source_name):
        frame_dir = Path(frame_dir)
        return {
            "path": str(frame_dir),
            "label": label,
            "dtype": "frame",
            "dataset": dataset_name,
            "source_split": None,
            "identity": self.get_identity(frame_dir.name),
            "frame_source": source_name,
        }

    def scan_frames(self):
        for source_name, frame_source in FRAME_DATASET_SOURCES.items():
            root = frame_source["root"]
            if not root.exists():
                continue

            if frame_source["layout"] == "video_mirror":
                for dataset_dir in sorted([p for p in root.iterdir() if p.is_dir()]):
                    dataset_name = dataset_dir.name
                    for frame_dir in dataset_dir.rglob("*"):
                        if not self._is_frame_dir(frame_dir):
                            continue
                        label = self._infer_label_from_path(frame_dir)
                        if label is None:
                            continue
                        record = self._frame_record(frame_dir, dataset_name, label, source_name)
                        self.records.append(record)
                        self.samples.append((record["path"], record["label"], record["dtype"]))

            elif frame_source["layout"] == "label_dataset_video":
                for label_dir in sorted([p for p in root.iterdir() if p.is_dir()]):
                    label = self._infer_label_from_path(label_dir)
                    if label is None:
                        continue
                    for dataset_dir in sorted([p for p in label_dir.iterdir() if p.is_dir()]):
                        dataset_name = dataset_dir.name
                        for frame_dir in dataset_dir.iterdir():
                            if not self._is_frame_dir(frame_dir):
                                continue
                            record = self._frame_record(frame_dir, dataset_name, label, source_name)
                            self.records.append(record)
                            self.samples.append((record["path"], record["label"], record["dtype"]))

    def build(self):
        print("\nScanning datasets...")
        self.records = []
        self.samples = []
        self.scan_images()
        self.scan_videos()
        self.scan_frames()
        print(f"Total samples: {len(self.samples)}")

    def _resolve_protocol(self, dtype=None, protocol=None):
        if protocol:
            return protocol
        if dtype == "image":
            return "image_only"
        if dtype == "video":
            return "video_only"
        if dtype == "frame":
            return "frame_only"
        return "combined_aux"

    def _filter_records(self, dtype=None, dataset_names=None):
        records = self.records
        if dtype:
            records = [record for record in records if record["dtype"] == dtype]
        if dataset_names:
            allowed = set(dataset_names)
            records = [record for record in records if record["dataset"] in allowed]
        return records

    def _split_records_random(self, records, train_ratio):
        rng = self._rng()
        records = list(records)
        rng.shuffle(records)
        cutoff = int(len(records) * train_ratio)
        return records[:cutoff], records[cutoff:]

    def _split_grouped_records(self, records, train_ratio=0.7, val_ratio=0.2):
        groups = defaultdict(list)
        for record in records:
            groups[record["identity"]].append(record)

        identities = list(groups.keys())
        rng = self._rng()
        rng.shuffle(identities)

        total = len(identities)
        train_end = int(total * train_ratio)
        val_end = int(total * (train_ratio + val_ratio))

        train = [record for identity in identities[:train_end] for record in groups[identity]]
        val = [record for identity in identities[train_end:val_end] for record in groups[identity]]
        test = [record for identity in identities[val_end:] for record in groups[identity]]
        return train, val, test

    def _prepare_image_only(self, records, val_ratio=DEFAULT_IMAGE_VAL_RATIO):
        train_records = []
        val_records = []
        test_records = []

        by_dataset = defaultdict(list)
        for record in records:
            by_dataset[record["dataset"]].append(record)

        for dataset_records in by_dataset.values():
            split_groups = defaultdict(list)
            for record in dataset_records:
                split_groups[record["source_split"]].append(record)

            train_source = split_groups.get("train", [])
            val_source = split_groups.get("val", [])
            test_source = split_groups.get("test", [])

            if val_source:
                local_train = train_source
                local_val = val_source
            else:
                local_train, local_val = self._split_records_random(train_source, 1.0 - val_ratio)

            if not train_source and not val_source and not test_source:
                local_train, local_val, local_test = self._split_grouped_records(dataset_records)
            else:
                local_test = test_source

            train_records.extend(local_train)
            val_records.extend(local_val)
            test_records.extend(local_test)

        return train_records, val_records, test_records

    def _prepare_video_only(self, records, train_ratio=DEFAULT_VIDEO_TRAIN_RATIO, val_ratio=DEFAULT_VIDEO_VAL_RATIO):
        train_records = []
        val_records = []
        test_records = []

        by_dataset = defaultdict(list)
        for record in records:
            by_dataset[record["dataset"]].append(record)

        for dataset_records in by_dataset.values():
            local_train, local_val, local_test = self._split_grouped_records(
                dataset_records,
                train_ratio=train_ratio,
                val_ratio=val_ratio,
            )
            train_records.extend(local_train)
            val_records.extend(local_val)
            test_records.extend(local_test)

        return train_records, val_records, test_records

    def _prepare_frame_only(self, records, train_ratio=DEFAULT_VIDEO_TRAIN_RATIO, val_ratio=DEFAULT_VIDEO_VAL_RATIO):
        return self._prepare_video_only(records, train_ratio=train_ratio, val_ratio=val_ratio)

    def _prepare_combined_aux(self, records, train_ratio=0.7, val_ratio=0.2):
        return self._split_grouped_records(records, train_ratio=train_ratio, val_ratio=val_ratio)

    def _apply_class_balance(self, records):
        if not records:
            return records

        counts = Counter(record["label"] for record in records)
        if len(counts) < 2:
            return records

        max_count = max(counts.values())
        rng = self._rng()
        balanced = []

        for label in sorted(counts.keys()):
            label_records = [record for record in records if record["label"] == label]
            repeats = max_count // len(label_records)
            remainder = max_count - len(label_records) * repeats
            balanced.extend(label_records * repeats)
            if remainder > 0:
                balanced.extend(rng.sample(label_records, remainder))

        rng.shuffle(balanced)
        return balanced

    def get_loaders(
        self,
        batch_size=32,
        mode="single",
        seq_len=DEFAULT_SEQUENCE_LEN,
        clip_sampling_train="random",
        clip_sampling_eval="center",
        dtype=None,
        protocol=None,
        dataset_names=None,
        balanced=True,
        train_ratio=DEFAULT_VIDEO_TRAIN_RATIO,
        val_ratio=None,
    ):
        self.build()
        resolved_protocol = self._resolve_protocol(dtype=dtype, protocol=protocol)
        filtered_records = self._filter_records(dtype=dtype, dataset_names=dataset_names)

        if val_ratio is None:
            if resolved_protocol in {"video_only", "frame_only"}:
                val_ratio = DEFAULT_VIDEO_VAL_RATIO
            else:
                val_ratio = 0.2

        if resolved_protocol == "image_only":
            train_records, val_records, test_records = self._prepare_image_only(filtered_records)
        elif resolved_protocol == "video_only":
            train_records, val_records, test_records = self._prepare_video_only(
                filtered_records,
                train_ratio=train_ratio,
                val_ratio=val_ratio,
            )
        elif resolved_protocol == "frame_only":
            train_records, val_records, test_records = self._prepare_frame_only(
                filtered_records,
                train_ratio=train_ratio,
                val_ratio=val_ratio,
            )
        elif resolved_protocol == "combined_aux":
            train_records, val_records, test_records = self._prepare_combined_aux(
                filtered_records,
                train_ratio=train_ratio,
                val_ratio=val_ratio,
            )
        else:
            raise ValueError(f"Unsupported protocol: {resolved_protocol}")

        if balanced:
            train_records = self._apply_class_balance(train_records)

        train = [self._record_to_sample(record) for record in train_records]
        val = [self._record_to_sample(record) for record in val_records]
        test = [self._record_to_sample(record) for record in test_records]

        tf_train = transforms.Compose([
            transforms.RandomResizedCrop(224, scale=(0.9, 1.0)),
            transforms.RandomHorizontalFlip(),
            transforms.ColorJitter(0.2, 0.2, 0.2),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
        ])
        tf_val = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
        ])

        print(
            f"\nPROTOCOL: {resolved_protocol} | datasets={dataset_names or 'all'} | "
            f"Train={len(train)}, Val={len(val)}, Test={len(test)}"
        )
        if resolved_protocol == "video_only":
            if mode == "single":
                print("VIDEO MODE: single | interpretation=spatial baseline on raw videos")
            elif mode == "sequence":
                print("VIDEO MODE: sequence | interpretation=spatial+temporal raw-video training")
        elif resolved_protocol == "image_only":
            print("IMAGE MODE: image-only spatial training")
        elif resolved_protocol == "frame_only":
            print("FRAME MODE: auxiliary derived-frame workflow")

        return (
            DataLoader(
                DeepFakeDataset(train, tf_train, mode, seq_len, clip_sampling=clip_sampling_train),
                **build_loader_kwargs(batch_size=batch_size, shuffle=True, drop_last=True),
            ),
            DataLoader(
                DeepFakeDataset(val, tf_val, mode, seq_len, clip_sampling=clip_sampling_eval),
                **build_loader_kwargs(batch_size=batch_size),
            ),
            DataLoader(
                DeepFakeDataset(test, tf_val, mode, seq_len, clip_sampling=clip_sampling_eval),
                **build_loader_kwargs(batch_size=batch_size),
            )
        )
