"""Unified dataset loading utilities for image and video deepfake experiments.

This module is the active data entrypoint used by training, evaluation, and data
inspection scripts.

Primary training path:
- image datasets feed image-only models
- raw video datasets feed video-only models
  - `mode="single"` acts as the spatial baseline on video data
  - `mode="sequence"` acts as the spatial+temporal path

Optional support remains for extracted frame folders, but frame materialization
is auxiliary and is not required for the default raw-video workflow.
"""

import os
import json
import random
import subprocess
import time
import cv2
import numpy as np
import warnings
from functools import lru_cache
from pathlib import Path
from collections import Counter, defaultdict, OrderedDict

# 🔥 Suppress FFmpeg/OpenCV noise
os.environ["OPENCV_LOG_LEVEL"] = "FATAL"
os.environ["FFMPEG_LOG_LEVEL"] = "quiet"

try:
    import decord
    from decord import VideoReader, cpu
    HAS_DECORD = True
except ImportError:
    HAS_DECORD = False

from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms

Image.MAX_IMAGE_PIXELS = None
warnings.filterwarnings("ignore", category=Image.DecompressionBombWarning)

# =========================
# CONFIG
# =========================

IMAGE_EXTS = [".jpg", ".jpeg", ".png", ".webp", ".bmp"]
VIDEO_EXTS = [".mp4", ".avi", ".mov", ".mkv"]
NUM_WORKERS = int(os.getenv("DF_NUM_WORKERS", "8"))
DEFAULT_IMAGE_VAL_RATIO = 0.15
DEFAULT_VIDEO_TRAIN_RATIO = 0.7
DEFAULT_VIDEO_VAL_RATIO = 0.1
DEFAULT_SEQUENCE_LEN = 8
DEFAULT_PREFETCH_FACTOR = int(os.getenv("DF_PREFETCH_FACTOR", "4"))
FFMPEG_BIN = os.getenv("DF_FFMPEG_BIN", "ffmpeg")
FFPROBE_BIN = os.getenv("DF_FFPROBE_BIN", "ffprobe")
# T1.8: root config override. Default value ("datasets") is unchanged, so any
# caller not setting DF_DATASET_ROOT gets identical behavior to before.
DEFAULT_DATASET_ROOT = os.getenv("DF_DATASET_ROOT", "datasets")
DEFAULT_STRIDE = 1
# T1.7: decode-failure policy is a MECHANISM only. Default is unchanged
# ("legacy_zero" == today's exact silent zero-tensor behavior). Switching the
# default is Open Decision #2 in FIXTURE_PLAN.md, gated on T1.0's blast-radius
# numbers -- do not change this default without that decision being made.
DECODE_FAILURE_POLICIES = {"legacy_zero", "raise"}
DEFAULT_DECODE_FAILURE_POLICY = os.getenv("DF_DECODE_FAILURE_POLICY", "legacy_zero")


def _ffmpeg_output_size():
    raw = os.getenv("DF_FFMPEG_OUTPUT_SIZE", "").strip()
    if not raw:
        return None
    try:
        size = int(raw)
        return size if size > 0 else None
    except ValueError:
        return None


def _bad_video_log_path():
    return os.getenv("DF_BAD_VIDEO_LOG_PATH", "train/video/bad_video_log.jsonl")


@lru_cache(maxsize=32768)
def _probe_video_meta_cached(path):
    meta = {"width": None, "height": None, "frames": None}
    try:
        cmd = [
            FFPROBE_BIN,
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_entries",
            "stream=width,height,nb_frames",
            "-of",
            "json",
            path,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        payload = json.loads(result.stdout or "{}")
        stream = (payload.get("streams") or [{}])[0]
        meta["width"] = int(stream["width"]) if stream.get("width") else None
        meta["height"] = int(stream["height"]) if stream.get("height") else None
        if stream.get("nb_frames") and str(stream["nb_frames"]).isdigit():
            meta["frames"] = int(stream["nb_frames"])
    except Exception:
        pass
    return meta

DATASET_CONFIG = {
    "images": {
        "ai-generated-images-vs-real-images": {"type": "image", "structure": "split_class", "classes": {"fake": 0, "real": 1}},
        "cifake": {"type": "image", "structure": "split_class", "classes": {"FAKE": 0, "REAL": 1}},
        # Optional derived dataset generated by datasets/extract_ff_frames.py
        "faceforensics_frames": {"type": "image", "structure": "split_class", "classes": {"fake": 0, "real": 1}},
    },
    "videos": {
        "celeb-df-v2": {
            "type": "video", "structure": "flat_class", 
            "classes": {"Celeb-real": 1, "YouTube-real": 1, "Celeb-fake": 0}
        },
        "faceforensics++": {
            "type": "video", "structure": "deep_nested",
            "rules": {"fake_paths": ["fake"], "real_paths": ["real"]}
        },
        "real-ai-videos": {
            "type": "video", "structure": "flat_class", 
            "classes": {"ai": 0, "fake": 0, "real": 1}
        }
    }
}

FRAME_DATASET_SOURCES = {
    "preprocessed_frames": {"root": Path("datasets/preprocessed_frames"), "layout": "video_mirror"},
    "video-frames": {"root": Path("video-frames"), "layout": "label_dataset_video"},
}


def build_loader_kwargs(batch_size, shuffle=False, drop_last=False):
    """Centralize DataLoader runtime settings for raw-video training."""
    kwargs = {
        "batch_size": batch_size,
        "shuffle": shuffle,
        "num_workers": NUM_WORKERS,
        "pin_memory": True,
        "drop_last": drop_last,
    }
    if NUM_WORKERS > 0:
        kwargs["persistent_workers"] = True
        kwargs["prefetch_factor"] = DEFAULT_PREFETCH_FACTOR
    return kwargs

# =========================
# DATASET
# =========================

class DeepFakeDataset(Dataset):
    def __init__(
        self,
        samples,
        transform=None,
        mode="single",
        seq_len=8,
        clip_sampling="random",
        stride=DEFAULT_STRIDE,
        decode_failure_policy=None,
    ):
        self.samples = samples
        self.transform = transform
        self.mode = mode
        self.seq_len = seq_len
        self.clip_sampling = clip_sampling
        self.stride = max(1, int(stride))
        resolved_policy = decode_failure_policy or DEFAULT_DECODE_FAILURE_POLICY
        if resolved_policy not in DECODE_FAILURE_POLICIES:
            raise ValueError(
                f"Unsupported decode_failure_policy: {resolved_policy!r}. "
                f"Supported: {sorted(DECODE_FAILURE_POLICIES)}"
            )
        self.decode_failure_policy = resolved_policy
        self._video_meta_cache = {}
        self._vr_cache = OrderedDict()
        self._vr_cache_limit = max(1, int(os.getenv("DF_VIDEO_READER_CACHE", "32")))
        self._bad_video_logged = set()

    def __len__(self):
        return len(self.samples)

    def _read_frame(self, cap, frame_id):
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_id)
        ret, frame = cap.read()
        return Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)) if ret else None

    def _video_decode_backend(self):
        return os.getenv("DF_VIDEO_DECODE_BACKEND", "auto").lower()

    def _log_bad_video(self, path, stage, detail):
        if not path or path in self._bad_video_logged:
            return
        self._bad_video_logged.add(path)
        try:
            log_path = Path(_bad_video_log_path())
            log_path.parent.mkdir(parents=True, exist_ok=True)
            payload = {
                "ts": int(time.time()),
                "path": path,
                "stage": stage,
                "detail": detail,
                "backend": self._video_decode_backend(),
                "mode": self.mode,
                "seq_len": self.seq_len,
            }
            with log_path.open("a", encoding="utf-8") as handle:
                handle.write(json.dumps(payload, ensure_ascii=True) + "\n")
        except Exception:
            pass

    def _use_decord_backend(self):
        backend = self._video_decode_backend()
        if not HAS_DECORD:
            return False
        return backend in {"decord", "decord_cpu"}

    def _get_decord_reader(self, path):
        reader = self._vr_cache.get(path)
        if reader is not None:
            self._vr_cache.move_to_end(path)
            return reader

        try:
            reader = VideoReader(path, ctx=cpu(0))
        except Exception as exc:
            self._log_bad_video(path, "decord_open", repr(exc))
            raise
        self._vr_cache[path] = reader
        if len(self._vr_cache) > self._vr_cache_limit:
            self._vr_cache.popitem(last=False)
        return reader

    def _ffmpeg_hwaccel_args(self):
        backend = self._video_decode_backend()
        if backend == "ffmpeg_qsv":
            return ["-hwaccel", "qsv"]
        if backend == "ffmpeg_d3d11va":
            return ["-hwaccel", "d3d11va"]
        return []

    def _ffmpeg_filter_expr(self, base_expr):
        filters = []
        output_size = _ffmpeg_output_size()
        if output_size:
            filters.append(f"scale={output_size}:{output_size}")
        filters.append(base_expr)
        filters.append("format=rgb24")
        return ",".join(filters)

    def _video_meta(self, path):
        cached = self._video_meta_cache.get(path)
        if cached is not None:
            return cached

        meta = dict(_probe_video_meta_cached(path))

        if meta["frames"] in {None, 0}:
            cap = cv2.VideoCapture(path)
            frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
            width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            cap.release()
            meta["frames"] = frames if frames > 0 else 0
            if meta["width"] is None and width > 0:
                meta["width"] = width
            if meta["height"] is None and height > 0:
                meta["height"] = height

        self._video_meta_cache[path] = meta
        return meta

    def _read_video_frame_ffmpeg(self, path, frame_id):
        meta = self._video_meta(path)
        width, height = meta["width"], meta["height"]
        if not width or not height:
            return None

        filter_expr = self._ffmpeg_filter_expr(f"select=eq(n\\,{frame_id})")
        cmd = [
            FFMPEG_BIN,
            "-hide_banner",
            "-loglevel",
            "error",
            *self._ffmpeg_hwaccel_args(),
            "-i",
            path,
            "-vf",
            filter_expr,
            "-vsync",
            "0",
            "-frames:v",
            "1",
            "-f",
            "rawvideo",
            "-pix_fmt",
            "rgb24",
            "-",
        ]
        try:
            result = subprocess.run(cmd, capture_output=True, check=True)
            output_size = _ffmpeg_output_size()
            if output_size:
                width = output_size
                height = output_size
            expected = width * height * 3
            if len(result.stdout) < expected:
                self._log_bad_video(path, "ffmpeg_single_short_read", f"bytes={len(result.stdout)} expected={expected}")
                return None
            frame = np.frombuffer(result.stdout[:expected], dtype=np.uint8).reshape(height, width, 3)
            return Image.fromarray(frame)
        except Exception as exc:
            self._log_bad_video(path, "ffmpeg_single", repr(exc))
            return None

    def _read_video_sequence_ffmpeg(self, path, indices):
        if not indices:
            return []
        meta = self._video_meta(path)
        width, height = meta["width"], meta["height"]
        if not width or not height:
            return []

        start = indices[0]
        end = indices[-1]
        filter_expr = self._ffmpeg_filter_expr(f"select=between(n\\,{start}\\,{end})")
        cmd = [
            FFMPEG_BIN,
            "-hide_banner",
            "-loglevel",
            "error",
            *self._ffmpeg_hwaccel_args(),
            "-i",
            path,
            "-vf",
            filter_expr,
            "-vsync",
            "0",
            "-frames:v",
            str(len(indices)),
            "-f",
            "rawvideo",
            "-pix_fmt",
            "rgb24",
            "-",
        ]
        try:
            result = subprocess.run(cmd, capture_output=True, check=True)
            output_size = _ffmpeg_output_size()
            if output_size:
                width = output_size
                height = output_size
            frame_bytes = width * height * 3
            raw = result.stdout
            if len(raw) < frame_bytes:
                self._log_bad_video(path, "ffmpeg_sequence_short_read", f"bytes={len(raw)} frame_bytes={frame_bytes}")
                return []
            frame_count = len(raw) // frame_bytes
            frames = []
            for offset in range(frame_count):
                start_byte = offset * frame_bytes
                end_byte = start_byte + frame_bytes
                frame = np.frombuffer(raw[start_byte:end_byte], dtype=np.uint8).reshape(height, width, 3)
                frames.append(Image.fromarray(frame))
            return frames
        except Exception as exc:
            self._log_bad_video(path, "ffmpeg_sequence", repr(exc))
            return []

    def _read_frame_dir_image(self, frame_files, index):
        if not frame_files:
            return Image.new("RGB", (224, 224))
        clamped = max(0, min(index, len(frame_files) - 1))
        return Image.open(frame_files[clamped]).convert("RGB")

    def _single_index(self, total_frames):
        if total_frames <= 0:
            return 0
        if self.clip_sampling == "center":
            return total_frames // 2
        return random.randint(0, total_frames - 1)

    def _list_frame_files(self, frame_dir):
        frame_dir = Path(frame_dir)
        return sorted(
            str(item)
            for item in frame_dir.iterdir()
            if item.is_file() and item.suffix.lower() in IMAGE_EXTS
        )

    def _contiguous_indices(self, total_frames):
        # T1.5: stride support. At stride=1 (the default) this produces
        # byte-identical output to the original implementation -- verified
        # by construction: span == self.seq_len when stride == 1, so every
        # branch below collapses to the original's logic exactly.
        stride = self.stride
        span = (self.seq_len - 1) * stride + 1

        if total_frames <= 0:
            return [0] * self.seq_len

        if total_frames <= span:
            if self.seq_len > 1:
                # Not enough frames to cover the requested stride*seq_len span.
                # Shrink stride to the tightest value that fits, rather than
                # silently ignoring the request or crashing.
                stride = max(1, (total_frames - 1) // (self.seq_len - 1))
                span = (self.seq_len - 1) * stride + 1
            if total_frames <= span:
                # Still doesn't fit even at stride=1 (very short video/clip):
                # pad by repeating the last available frame, same as before.
                base = list(range(min(total_frames, self.seq_len)))
                return base + [max(total_frames - 1, 0)] * (self.seq_len - len(base))

        if self.clip_sampling == "center":
            start = max((total_frames - span) // 2, 0)
        else:
            start = random.randint(0, total_frames - span)
        return [start + i * stride for i in range(self.seq_len)]

    def __getitem__(self, idx):
        path, label, dtype = self.samples[idx]
        try:
            if self.mode == "single":
                if dtype == "image":
                    img = Image.open(path).convert("RGB")
                elif dtype == "video":
                    if self._use_decord_backend():
                        try:
                            vr = self._get_decord_reader(path)
                            img = Image.fromarray(vr[self._single_index(len(vr))].asnumpy())
                        except Exception:
                            img = None
                        if img is None:
                            self._log_bad_video(path, "decord_single_fallback", "falling back to non-decord path")
                            meta = self._video_meta(path)
                            frame_id = self._single_index(meta["frames"] or 0)
                            if self._video_decode_backend() in {"ffmpeg", "ffmpeg_qsv", "ffmpeg_d3d11va"}:
                                img = self._read_video_frame_ffmpeg(path, frame_id)
                            if img is None:
                                cap = cv2.VideoCapture(path)
                                img = self._read_frame(cap, frame_id)
                                cap.release()
                    else:
                        meta = self._video_meta(path)
                        frame_id = self._single_index(meta["frames"] or 0)
                        img = None
                        if self._video_decode_backend() in {"ffmpeg", "ffmpeg_qsv", "ffmpeg_d3d11va"}:
                            img = self._read_video_frame_ffmpeg(path, frame_id)
                        if img is None:
                            cap = cv2.VideoCapture(path)
                            img = self._read_frame(cap, frame_id)
                            cap.release()
                    if img is None:
                        self._log_bad_video(path, "video_single_none", "all decode paths returned None")
                        img = Image.new("RGB", (224, 224))
                elif dtype == "frame":
                    frame_files = self._list_frame_files(path)
                    img = self._read_frame_dir_image(frame_files, self._single_index(len(frame_files)))
                if self.transform: img = self.transform(img)
                return img, label

            elif self.mode == "sequence":
                if dtype == "frame":
                    frame_files = self._list_frame_files(path)
                    indices = self._contiguous_indices(len(frame_files))
                    frames = []
                    for i in indices:
                        img = self._read_frame_dir_image(frame_files, i)
                        if self.transform:
                            img = self.transform(img)
                        frames.append(img)
                    return torch.stack(frames), label
                if self._use_decord_backend():
                    try:
                        vr = self._get_decord_reader(path)
                        indices = self._contiguous_indices(len(vr))
                        frames = [Image.fromarray(f.asnumpy()) for f in vr.get_batch(indices)]
                        if self.transform: frames = [self.transform(f) for f in frames]
                        return torch.stack(frames), label
                    except Exception:
                        self._log_bad_video(path, "decord_sequence_fallback", "falling back to non-decord path")
                else:
                    meta = self._video_meta(path)
                    indices = self._contiguous_indices(meta["frames"] or 0)
                    pil_frames = []
                    if self._video_decode_backend() in {"ffmpeg", "ffmpeg_qsv", "ffmpeg_d3d11va"}:
                        pil_frames = self._read_video_sequence_ffmpeg(path, indices)
                    if not pil_frames:
                        cap = cv2.VideoCapture(path)
                        pil_frames = []
                        for i in indices:
                            img = self._read_frame(cap, i)
                            if img is None: img = pil_frames[-1] if pil_frames else Image.new('RGB', (224, 224))
                            pil_frames.append(img)
                        cap.release()
                    if len(pil_frames) < len(indices):
                        pad = pil_frames[-1] if pil_frames else Image.new("RGB", (224, 224))
                        pil_frames.extend([pad] * (len(indices) - len(pil_frames)))
                    frames = []
                    for img in pil_frames[: len(indices)]:
                        if self.transform: img = self.transform(img)
                        frames.append(img)
                    if not frames:
                        self._log_bad_video(path, "video_sequence_empty", "all decode paths returned empty sequence")
                        frames = [torch.zeros((3, 224, 224)) for _ in range(self.seq_len)]
                    return torch.stack(frames), label
            raise ValueError(f"Unsupported mode: {self.mode}")
        except Exception as exc:
            if dtype == "video":
                self._log_bad_video(path, "getitem_exception", repr(exc))
            # T1.7: decode-failure policy. Default ("legacy_zero") falls through
            # to the exact original behavior below -- silent zero-tensor with
            # the original label, unflagged. "raise" is the only other wired
            # policy right now; "zero_with_flag" is deliberately NOT implemented
            # here because it requires changing the __getitem__ return contract
            # (2-tuple -> 3-tuple) on every call site, which needs to land
            # together with the trainer-side consumer of that flag (T2b), not
            # silently in the data layer alone. See FIXTURE_PLAN.md T1.7/S7#2.
            if self.decode_failure_policy == "raise":
                raise
            shape = (3, 224, 224) if self.mode == "single" else (self.seq_len, 3, 224, 224)
            return torch.zeros(shape), label

# =========================
# BUILDER
# =========================

class _LegacyDatasetBuilder:
    def __init__(self, root=None):
        # T1.8: root=None resolves to DEFAULT_DATASET_ROOT (env DF_DATASET_ROOT,
        # falling back to "datasets" -- identical to the old hardcoded default).
        self.root = Path(root if root is not None else DEFAULT_DATASET_ROOT)
        self.samples = []

    def _is_image_file(self, path):
        return path.is_file() and path.suffix.lower() in IMAGE_EXTS

    def _is_video_file(self, path):
        return path.is_file() and path.suffix.lower() in VIDEO_EXTS

    def _is_frame_dir(self, path):
        if not path.is_dir():
            return False
        return any(item.is_file() and item.suffix.lower() in IMAGE_EXTS for item in path.iterdir())

    def _infer_label_from_path(self, path):
        parts = [part.lower() for part in Path(path).parts]
        if "real" in parts or "youtube-real" in parts or "celeb-real" in parts:
            return 1
        if "fake" in parts or "celeb-fake" in parts or "ai" in parts:
            return 0
        path_str = str(path).lower().replace("\\", "/")
        if "/real/" in path_str:
            return 1
        if "/fake/" in path_str or "/ai/" in path_str:
            return 0
        return None

    def get_identity(self, path):
        """Extracts Person ID for subject-independent splitting."""
        name = Path(path).name.lower()
        # CelebDF: id0_id1_0000.mp4 -> id0
        if name.startswith("id"):
            return name.split("_")[0]
        # FF++: 000_001.mp4 -> 000
        if "_" in name and name[:3].isdigit():
            return name.split("_")[0]
        # Fallback to full path (treat as unique identity)
        return path

    def scan_images(self):
        root = self.root / "images"
        if not root.exists(): return
        for ds, cfg in DATASET_CONFIG["images"].items():
            ds_path = root / ds
            if not ds_path.exists(): continue
            # Discover split folders from disk instead of assuming only train/test.
            for split_dir in sorted([p for p in ds_path.iterdir() if p.is_dir()]):
                split = split_dir.name
                if split.startswith("."):
                    continue
                for cls, label in cfg["classes"].items():
                    cls_dir = split_dir / cls
                    if not cls_dir.exists(): continue
                    for img in cls_dir.rglob("*"):
                        if not self._is_image_file(img):
                            continue
                        self.samples.append((str(img), label, "image"))

    def scan_videos(self):
        root = self.root / "videos"
        if not root.exists(): return
        for ds, cfg in DATASET_CONFIG["videos"].items():
            ds_path = root / ds
            if not ds_path.exists(): continue
            if cfg["structure"] == "flat_class":
                for cls, label in cfg["classes"].items():
                    cls_dir = ds_path / cls
                    if cls_dir.exists():
                        for v in cls_dir.rglob("*"):
                            if self._is_video_file(v):
                                self.samples.append((str(v), label, "video"))
            elif cfg["structure"] == "deep_nested":
                for p in cfg["rules"]["fake_paths"]:
                    d = ds_path / p
                    if d.exists():
                        for v in d.rglob("*"):
                            if self._is_video_file(v):
                                self.samples.append((str(v), 0, "video"))
                for p in cfg["rules"]["real_paths"]:
                    d = ds_path / p
                    if d.exists():
                        for v in d.rglob("*"):
                            if self._is_video_file(v):
                                self.samples.append((str(v), 1, "video"))

    def scan_frames(self):
        for frame_source in FRAME_DATASET_SOURCES.values():
            root = frame_source["root"]
            if not root.exists():
                continue

            for frame_dir in root.rglob("*"):
                if not self._is_frame_dir(frame_dir):
                    continue

                label = self._infer_label_from_path(frame_dir)
                if label is None:
                    continue

                self.samples.append((str(frame_dir), label, "frame"))

    def build(self):
        print("\n🔍 Scanning datasets...")
        self.samples = []
        self.scan_images(); self.scan_videos(); self.scan_frames()
        print(f"Total samples: {len(self.samples)}")

    def split_samples(self, samples, train_ratio=0.7, val_ratio=0.2):
        """Subject-Independent Split: Group by Person ID."""
        groups = {}
        for s in samples:
            identity = self.get_identity(s[0])
            if identity not in groups: groups[identity] = []
            groups[identity].append(s)
        
        identities = list(groups.keys())
        random.shuffle(identities)
        
        n = len(identities)
        t_idx, v_idx = int(n * train_ratio), int(n * (train_ratio + val_ratio))
        
        train = [s for i in identities[:t_idx] for s in groups[i]]
        val = [s for i in identities[t_idx:v_idx] for s in groups[i]]
        test = [s for i in identities[v_idx:] for s in groups[i]]
        
        print(f"👥 Unique Identities found: {len(identities)}")
        return train, val, test

    def get_loaders(self, batch_size=32, mode="single", seq_len=8, dtype=None, balanced=True):
        self.build()
        filtered = [s for s in self.samples if s[2] == dtype] if dtype else self.samples
        train, val, test = self.split_samples(filtered)

        tf_train = transforms.Compose([
            transforms.RandomResizedCrop(224, scale=(0.9, 1.0)),
            transforms.RandomHorizontalFlip(),
            transforms.ColorJitter(0.2, 0.2, 0.2),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])
        tf_val = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])

        if balanced:
            counts = Counter([s[1] for s in train])
            max_c = max(counts.values())
            balanced_train = []
            for label in counts.keys():
                cls_s = [s for s in train if s[1] == label]
                mult = max_c // len(cls_s)
                balanced_train.extend(cls_s * mult)
                balanced_train.extend(random.sample(cls_s, max_c - len(cls_s)*mult))
            train = balanced_train

        print(f"\n📊 SPLIT: Train={len(train)}, Val={len(val)}, Test={len(test)}")
        
        return (
            DataLoader(DeepFakeDataset(train, tf_train, mode, seq_len), batch_size=batch_size, shuffle=True, num_workers=NUM_WORKERS, pin_memory=True, drop_last=True),
            DataLoader(DeepFakeDataset(val, tf_val, mode, seq_len), batch_size=batch_size, num_workers=NUM_WORKERS, pin_memory=True),
            DataLoader(DeepFakeDataset(test, tf_val, mode, seq_len), batch_size=batch_size, num_workers=NUM_WORKERS, pin_memory=True)
        )


class DatasetBuilder(_LegacyDatasetBuilder):
    """Protocol-aware dataset builder.

    Defaults:
    - dtype='image' -> protocol='image_only'
    - dtype='video' -> protocol='video_only'
    - dtype='frame' -> protocol='frame_only'
    - dtype=None -> protocol='combined_aux'

    Research interpretation:
    - image_only -> image-model path
    - video_only + single -> spatial baseline on videos
    - video_only + sequence -> spatial+temporal training path
    - frame_only -> auxiliary derived-frame experiments
    """

    def __init__(self, root=None, seed=42, manifest_path=None):
        super().__init__(root=root)
        self.seed = seed
        self.records = []
        # T3: optional integrity-manifest-driven filtering. None (default) =
        # unchanged behavior, every discovered file is kept, exactly as
        # before. When set, build() drops files the manifest marked invalid
        # (produced by `python -m proc.integrity_scan`) -- this is the
        # "drop" decode-failure policy T1.7 deliberately deferred to here,
        # since dropping requires a pre-computed validity list, not a
        # per-__getitem__ decision.
        self.manifest_path = manifest_path

    def _rng(self):
        return random.Random(self.seed)

    def _record_to_sample(self, record):
        return (record["path"], record["label"], record["dtype"])

    def scan_images(self):
        root = self.root / "images"
        if not root.exists():
            return

        for dataset_name, cfg in DATASET_CONFIG["images"].items():
            ds_path = root / dataset_name
            if not ds_path.exists():
                continue

            for split_dir in sorted([p for p in ds_path.iterdir() if p.is_dir()]):
                split_name = split_dir.name.lower()
                if split_name.startswith("."):
                    continue

                for class_name, label in cfg["classes"].items():
                    cls_dir = split_dir / class_name
                    if not cls_dir.exists():
                        continue

                    for img_path in cls_dir.rglob("*"):
                        if not self._is_image_file(img_path):
                            continue

                        self.records.append(
                            {
                                "path": str(img_path),
                                "label": label,
                                "dtype": "image",
                                "dataset": dataset_name,
                                "source_split": split_name,
                                "identity": str(img_path),
                            }
                        )
                        self.samples.append((str(img_path), label, "image"))

    def scan_videos(self):
        root = self.root / "videos"
        if not root.exists():
            return

        for dataset_name, cfg in DATASET_CONFIG["videos"].items():
            ds_path = root / dataset_name
            if not ds_path.exists():
                continue

            if cfg["structure"] == "flat_class":
                for class_name, label in cfg["classes"].items():
                    cls_dir = ds_path / class_name
                    if not cls_dir.exists():
                        continue

                    for video_path in cls_dir.rglob("*"):
                        if not self._is_video_file(video_path):
                            continue

                        record = {
                            "path": str(video_path),
                            "label": label,
                            "dtype": "video",
                            "dataset": dataset_name,
                            "source_split": None,
                            "identity": self.get_identity(str(video_path)),
                        }
                        self.records.append(record)
                        self.samples.append((record["path"], record["label"], record["dtype"]))

            elif cfg["structure"] == "deep_nested":
                for rel_path in cfg["rules"]["fake_paths"]:
                    nested_dir = ds_path / rel_path
                    if not nested_dir.exists():
                        continue

                    for video_path in nested_dir.rglob("*"):
                        if not self._is_video_file(video_path):
                            continue

                        record = {
                            "path": str(video_path),
                            "label": 0,
                            "dtype": "video",
                            "dataset": dataset_name,
                            "source_split": None,
                            "identity": self.get_identity(str(video_path)),
                        }
                        self.records.append(record)
                        self.samples.append((record["path"], record["label"], record["dtype"]))

                for rel_path in cfg["rules"]["real_paths"]:
                    nested_dir = ds_path / rel_path
                    if not nested_dir.exists():
                        continue

                    for video_path in nested_dir.rglob("*"):
                        if not self._is_video_file(video_path):
                            continue

                        record = {
                            "path": str(video_path),
                            "label": 1,
                            "dtype": "video",
                            "dataset": dataset_name,
                            "source_split": None,
                            "identity": self.get_identity(str(video_path)),
                        }
                        self.records.append(record)
                        self.samples.append((record["path"], record["label"], record["dtype"]))

    def _frame_record(self, frame_dir, dataset_name, label, source_name):
        frame_dir = Path(frame_dir)
        return {
            "path": str(frame_dir),
            "label": label,
            "dtype": "frame",
            "dataset": dataset_name,
            "source_split": None,
            "identity": self.get_identity(frame_dir.name),
            "frame_source": source_name,
        }

    def scan_frames(self):
        for source_name, frame_source in FRAME_DATASET_SOURCES.items():
            root = frame_source["root"]
            if not root.exists():
                continue

            if frame_source["layout"] == "video_mirror":
                for dataset_dir in sorted([p for p in root.iterdir() if p.is_dir()]):
                    dataset_name = dataset_dir.name
                    for frame_dir in dataset_dir.rglob("*"):
                        if not self._is_frame_dir(frame_dir):
                            continue
                        label = self._infer_label_from_path(frame_dir)
                        if label is None:
                            continue
                        record = self._frame_record(frame_dir, dataset_name, label, source_name)
                        self.records.append(record)
                        self.samples.append((record["path"], record["label"], record["dtype"]))

            elif frame_source["layout"] == "label_dataset_video":
                for label_dir in sorted([p for p in root.iterdir() if p.is_dir()]):
                    label = self._infer_label_from_path(label_dir)
                    if label is None:
                        continue
                    for dataset_dir in sorted([p for p in label_dir.iterdir() if p.is_dir()]):
                        dataset_name = dataset_dir.name
                        for frame_dir in dataset_dir.iterdir():
                            if not self._is_frame_dir(frame_dir):
                                continue
                            record = self._frame_record(frame_dir, dataset_name, label, source_name)
                            self.records.append(record)
                            self.samples.append((record["path"], record["label"], record["dtype"]))

    def build(self):
        print("\nScanning datasets...")
        self.records = []
        self.samples = []
        self.scan_images()
        self.scan_videos()
        self.scan_frames()
        print(f"Total samples: {len(self.samples)}")
        if self.manifest_path:
            self._apply_manifest_filter()

    def _apply_manifest_filter(self):
        from proc.manifest import load_manifest

        manifest = load_manifest(self.manifest_path)
        invalid = manifest.invalid_paths()
        if not invalid:
            print(f"Manifest {self.manifest_path}: 0 invalid files, nothing filtered.")
            return

        before = len(self.samples)
        self.samples = [s for s in self.samples if s[0] not in invalid]
        self.records = [r for r in self.records if r["path"] not in invalid]
        removed = before - len(self.samples)
        print(
            f"Manifest {self.manifest_path}: dropped {removed} sample(s) marked invalid "
            f"({len(invalid)} total invalid entries in manifest, some may not match current discovery)."
        )

    def _resolve_protocol(self, dtype=None, protocol=None):
        if protocol:
            return protocol
        if dtype == "image":
            return "image_only"
        if dtype == "video":
            return "video_only"
        if dtype == "frame":
            return "frame_only"
        return "combined_aux"

    def _filter_records(self, dtype=None, dataset_names=None):
        records = self.records
        if dtype:
            records = [record for record in records if record["dtype"] == dtype]
        if dataset_names:
            allowed = set(dataset_names)
            records = [record for record in records if record["dataset"] in allowed]
        return records

    def _split_records_random(self, records, train_ratio):
        rng = self._rng()
        records = list(records)
        rng.shuffle(records)
        cutoff = int(len(records) * train_ratio)
        return records[:cutoff], records[cutoff:]

    def _split_grouped_records(self, records, train_ratio=0.7, val_ratio=0.2):
        groups = defaultdict(list)
        for record in records:
            groups[record["identity"]].append(record)

        identities = list(groups.keys())
        rng = self._rng()
        rng.shuffle(identities)

        total = len(identities)
        train_end = int(total * train_ratio)
        val_end = int(total * (train_ratio + val_ratio))

        train = [record for identity in identities[:train_end] for record in groups[identity]]
        val = [record for identity in identities[train_end:val_end] for record in groups[identity]]
        test = [record for identity in identities[val_end:] for record in groups[identity]]
        return train, val, test

    def _prepare_image_only(self, records, val_ratio=DEFAULT_IMAGE_VAL_RATIO):
        train_records = []
        val_records = []
        test_records = []

        by_dataset = defaultdict(list)
        for record in records:
            by_dataset[record["dataset"]].append(record)

        for dataset_records in by_dataset.values():
            split_groups = defaultdict(list)
            for record in dataset_records:
                split_groups[record["source_split"]].append(record)

            train_source = split_groups.get("train", [])
            val_source = split_groups.get("val", [])
            test_source = split_groups.get("test", [])

            if val_source:
                local_train = train_source
                local_val = val_source
            else:
                local_train, local_val = self._split_records_random(train_source, 1.0 - val_ratio)

            if not train_source and not val_source and not test_source:
                local_train, local_val, local_test = self._split_grouped_records(dataset_records)
            else:
                local_test = test_source

            train_records.extend(local_train)
            val_records.extend(local_val)
            test_records.extend(local_test)

        return train_records, val_records, test_records

    def _prepare_video_only(self, records, train_ratio=DEFAULT_VIDEO_TRAIN_RATIO, val_ratio=DEFAULT_VIDEO_VAL_RATIO):
        train_records = []
        val_records = []
        test_records = []

        by_dataset = defaultdict(list)
        for record in records:
            by_dataset[record["dataset"]].append(record)

        for dataset_records in by_dataset.values():
            local_train, local_val, local_test = self._split_grouped_records(
                dataset_records,
                train_ratio=train_ratio,
                val_ratio=val_ratio,
            )
            train_records.extend(local_train)
            val_records.extend(local_val)
            test_records.extend(local_test)

        return train_records, val_records, test_records

    def _prepare_frame_only(self, records, train_ratio=DEFAULT_VIDEO_TRAIN_RATIO, val_ratio=DEFAULT_VIDEO_VAL_RATIO):
        return self._prepare_video_only(records, train_ratio=train_ratio, val_ratio=val_ratio)

    def _prepare_combined_aux(self, records, train_ratio=0.7, val_ratio=0.2):
        return self._split_grouped_records(records, train_ratio=train_ratio, val_ratio=val_ratio)

    def _apply_class_balance(self, records):
        if not records:
            return records

        counts = Counter(record["label"] for record in records)
        if len(counts) < 2:
            return records

        max_count = max(counts.values())
        rng = self._rng()
        balanced = []

        for label in sorted(counts.keys()):
            label_records = [record for record in records if record["label"] == label]
            repeats = max_count // len(label_records)
            remainder = max_count - len(label_records) * repeats
            balanced.extend(label_records * repeats)
            if remainder > 0:
                balanced.extend(rng.sample(label_records, remainder))

        rng.shuffle(balanced)
        return balanced

    def get_loaders(
        self,
        batch_size=32,
        mode="single",
        seq_len=DEFAULT_SEQUENCE_LEN,
        clip_sampling_train="random",
        clip_sampling_eval="center",
        dtype=None,
        protocol=None,
        dataset_names=None,
        balanced=True,
        train_ratio=DEFAULT_VIDEO_TRAIN_RATIO,
        val_ratio=None,
        train_transform=None,
        eval_transform=None,
        split_engine="legacy",
        stride=DEFAULT_STRIDE,
        decode_failure_policy=None,
    ):
        split_bundle = self.prepare_records(
            dtype=dtype,
            protocol=protocol,
            dataset_names=dataset_names,
            balanced=balanced,
            train_ratio=train_ratio,
            val_ratio=val_ratio,
            split_engine=split_engine,
        )
        resolved_protocol = split_bundle["protocol"]
        train_records = split_bundle["train"]
        val_records = split_bundle["val"]
        test_records = split_bundle["test"]

        train = [self._record_to_sample(record) for record in train_records]
        val = [self._record_to_sample(record) for record in val_records]
        test = [self._record_to_sample(record) for record in test_records]

        tf_train = train_transform or transforms.Compose([
            transforms.RandomResizedCrop(224, scale=(0.9, 1.0)),
            transforms.RandomHorizontalFlip(),
            transforms.ColorJitter(0.2, 0.2, 0.2),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
        ])
        tf_val = eval_transform or transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
        ])

        print(
            f"\nPROTOCOL: {resolved_protocol} | datasets={dataset_names or 'all'} | "
            f"Train={len(train)}, Val={len(val)}, Test={len(test)}"
        )
        if resolved_protocol == "video_only":
            if mode == "single":
                print("VIDEO MODE: single | interpretation=spatial baseline on raw videos")
            elif mode == "sequence":
                print("VIDEO MODE: sequence | interpretation=spatial+temporal raw-video training")
        elif resolved_protocol == "image_only":
            print("IMAGE MODE: image-only spatial training")
        elif resolved_protocol == "frame_only":
            print("FRAME MODE: auxiliary derived-frame workflow")

        return (
            DataLoader(
                DeepFakeDataset(
                    train, tf_train, mode, seq_len, clip_sampling=clip_sampling_train,
                    stride=stride, decode_failure_policy=decode_failure_policy,
                ),
                **build_loader_kwargs(batch_size=batch_size, shuffle=True, drop_last=True),
            ),
            DataLoader(
                DeepFakeDataset(
                    val, tf_val, mode, seq_len, clip_sampling=clip_sampling_eval,
                    stride=stride, decode_failure_policy=decode_failure_policy,
                ),
                **build_loader_kwargs(batch_size=batch_size),
            ),
            DataLoader(
                DeepFakeDataset(
                    test, tf_val, mode, seq_len, clip_sampling=clip_sampling_eval,
                    stride=stride, decode_failure_policy=decode_failure_policy,
                ),
                **build_loader_kwargs(batch_size=batch_size),
            )
        )

    def _prepare_video_identity_v2(
        self,
        records,
        train_ratio=DEFAULT_VIDEO_TRAIN_RATIO,
        val_ratio=DEFAULT_VIDEO_VAL_RATIO,
        max_clips=8,
    ):
        """T1.3/T1.4: identity-disjoint split via data/splits.py, with a hard,
        non-bypassable leakage check, plus asymmetric clip-count balancing.

        NOT the default (split_engine="identity_v2" opt-in only) -- see the
        module-level note above DATASET_REGISTRY in data/dataset_registry.py
        and FIXTURE_PLAN.md T1.3 for why: this groups FF++ actor-pair files
        and Celeb-DF two-identity fake videos correctly, which the legacy
        path did not, so split composition (and therefore counts) differs
        from the legacy path by design, not by bug.

        Returns (train, val, test) as plain dict records in the SAME shape
        _prepare_video_only returns, so callers don't need to know which
        engine produced them. Train records are repeated per-video according
        to the asymmetric balance (n_clips); DeepFakeDataset's per-call
        random clip-start sampling means each repetition yields a different
        sampled clip across epochs without any DeepFakeDataset changes.
        """
        from collections import defaultdict as _defaultdict
        from data.splits import build_record, assign_splits, check_leakage, balance_by_clip_sampling, summarize

        by_dataset = _defaultdict(list)
        for record in records:
            by_dataset[record["dataset"]].append(record)

        train_out, val_out, test_out = [], [], []
        ratios = (train_ratio, val_ratio, max(0.0, 1.0 - train_ratio - val_ratio))

        for dataset_name, dataset_records in by_dataset.items():
            if dataset_name == "faceforensics++":
                from data.identity import detect_ffpp_manipulation

                video_records = [
                    build_record(
                        r["path"], label=r["label"], dataset=dataset_name,
                        manipulation=detect_ffpp_manipulation(r["path"]),
                    )
                    for r in dataset_records
                ]
            else:
                video_records = [
                    build_record(r["path"], label=r["label"], dataset=dataset_name)
                    for r in dataset_records
                ]

            if dataset_name == "celeb-df-v2":
                assigned = self._assign_celebdf_splits(video_records, ratios=ratios)
            else:
                assigned = assign_splits(video_records, seed=self.seed, ratios=ratios)
                leaks = check_leakage(assigned)
                if leaks:
                    raise RuntimeError(
                        f"Identity leakage detected in dataset {dataset_name!r}, refusing to "
                        f"build a split: {leaks[:10]}{' ...(+more)' if len(leaks) > 10 else ''}"
                    )

            balance_by_clip_sampling(assigned, split="train", max_clips=max_clips)
            print(f"[identity_v2] {dataset_name}:")
            print(summarize(assigned))

            source_by_path = {r["path"]: r for r in dataset_records}
            for video_record in assigned:
                source = source_by_path[video_record.path]
                target = {"train": train_out, "val": val_out, "test": test_out}[video_record.split]
                repeats = video_record.n_clips if video_record.split == "train" else 1
                for _ in range(max(1, repeats)):
                    target.append(dict(source))

        return train_out, val_out, test_out

    def _assign_celebdf_splits(self, video_records, ratios):
        """Celeb-DF-v2 special case: honor the dataset's official published
        test list instead of running the generic identity-graph split on it.

        Why: verified empirically (see FIXTURE_PLAN.md S7 Open Decision #8)
        that celeb-df-v2's fake videos densely cross-link identities into a
        few giant connected components, so a generic union-find identity
        split can produce a 0%-real val/test split. The dataset's own
        authors solved this by hand-curating List_of_testing_videos.txt
        (178 real / 340 fake, verified against the file). The standard
        community protocol for this dataset trains on everything NOT in
        that list and evaluates on it -- WITHOUT an additional identity-
        disjointness requirement between the official test set and the
        training pool, since the official split is the accepted benchmark
        contract, not an artifact needing further leakage-proofing. Every
        published Celeb-DF-v2 result uses this same protocol; enforcing our
        own additional identity-disjointness on top of it would make results
        incomparable to the literature for no correctness benefit.

        check_leakage() therefore only runs on the (train, val) remainder we
        still control, not across the official-test boundary -- that
        boundary is fixed by the dataset's publishers, not us.
        """
        from data.splits import (
            assign_splits, check_leakage, load_celebdf_official_test_list,
            is_in_celebdf_official_test,
        )

        official_list_path = self.root / "videos" / "celeb-df-v2" / "List_of_testing_videos.txt"
        if not official_list_path.exists():
            print(
                f"[identity_v2] celeb-df-v2: official test list not found at "
                f"{official_list_path} -- falling back to the generic identity-graph "
                f"split for this dataset (may produce a low-real-content eval split; "
                f"see FIXTURE_PLAN.md S7 Open Decision #8)."
            )
            assigned = assign_splits(video_records, seed=self.seed, ratios=ratios)
            leaks = check_leakage(assigned)
            if leaks:
                raise RuntimeError(
                    f"Identity leakage detected in celeb-df-v2, refusing to build a split: "
                    f"{leaks[:10]}{' ...(+more)' if len(leaks) > 10 else ''}"
                )
            return assigned

        official_entries = load_celebdf_official_test_list(official_list_path)
        official_test = []
        remaining = []
        for record in video_records:
            if is_in_celebdf_official_test(record.path, official_entries):
                record.split = "test"
                official_test.append(record)
            else:
                remaining.append(record)

        train_ratio, val_ratio, _test_ratio = ratios
        pool = train_ratio + val_ratio
        remainder_ratios = (
            (train_ratio / pool, val_ratio / pool, 0.0) if pool > 0 else (0.7, 0.3, 0.0)
        )
        remaining_assigned = assign_splits(remaining, seed=self.seed, ratios=remainder_ratios)

        leaks = check_leakage(remaining_assigned)
        if leaks:
            raise RuntimeError(
                f"Identity leakage detected WITHIN the celeb-df-v2 train/val remainder "
                f"(official test boundary is intentionally excluded from this check -- "
                f"see _assign_celebdf_splits docstring), refusing to build a split: "
                f"{leaks[:10]}{' ...(+more)' if len(leaks) > 10 else ''}"
            )

        print(
            f"[identity_v2] celeb-df-v2: using official test list "
            f"({len(official_test)} videos: "
            f"{sum(1 for r in official_test if r.label == 1)} real, "
            f"{sum(1 for r in official_test if r.label == 0)} fake) "
            f"-- train/val identity-split over the remaining {len(remaining)} videos"
        )
        return remaining_assigned + official_test

    def prepare_lomo_split(self, lomo_config, train_ratio=DEFAULT_VIDEO_TRAIN_RATIO, val_ratio=DEFAULT_VIDEO_VAL_RATIO):
        """T2b: leave-one-manipulation-out. Builds an identity_v2 split over
        faceforensics++ (the only dataset with a manipulation-type concept --
        Celeb-DF/real-ai-videos have none), then partitions it into
        (train_pool, unseen_test_pool) for the given LOMO config via
        data/splits.py:filter_for_lomo.

        Only `lomo_config["test_manipulation"]` is trusted from the input --
        `train_manipulations` is ALWAYS rebuilt here from the manipulations
        actually present in the discovered corpus, minus the held-out one.
        This is deliberate, not redundant with data/splits.py:usable_lomo_configs():
        a real bug was caught during this session where a raw lomo_configs()
        entry's train_manipulations (the nominal 4 standard FF++ manipulations)
        silently excluded every DeepFakeDetection fake video from training --
        not held out as unseen, not trained on, just dropped, because
        "DeepFakeDetection" was never one of the 4 standard names. Rebuilding
        here means that mistake can't recur even if a caller passes a raw,
        unfiltered config instead of usable_lomo_configs()'s output.

        Returns (train_samples, test_samples) as (path, label, dtype) tuples,
        the same shape DeepFakeDataset already consumes.
        """
        from data.identity import detect_ffpp_manipulation
        from data.splits import build_record, assign_splits, check_leakage, filter_for_lomo, manipulations_present

        self.build()
        ffpp_records = self._filter_records(dtype="video", dataset_names=["faceforensics++"])
        video_records = [
            build_record(
                r["path"], label=r["label"], dataset="faceforensics++",
                manipulation=detect_ffpp_manipulation(r["path"]),
            )
            for r in ffpp_records
        ]

        present = manipulations_present(video_records)
        test_manipulation = lomo_config["test_manipulation"]
        if test_manipulation not in present:
            raise ValueError(
                f"LOMO test_manipulation {test_manipulation!r} is not present in this corpus "
                f"(present: {sorted(present)}). Use data/splits.py:usable_lomo_configs() to "
                f"only generate configs this corpus can actually run."
            )
        resolved_config = dict(lomo_config)
        resolved_config["train_manipulations"] = sorted(present - {test_manipulation})

        ratios = (train_ratio, val_ratio, max(0.0, 1.0 - train_ratio - val_ratio))
        assigned = assign_splits(video_records, seed=self.seed, ratios=ratios)
        leaks = check_leakage(assigned)
        if leaks:
            raise RuntimeError(
                f"Identity leakage detected while building the LOMO base split, refusing to "
                f"proceed: {leaks[:10]}{' ...(+more)' if len(leaks) > 10 else ''}"
            )

        train_pool, test_pool = filter_for_lomo(assigned, resolved_config)
        train_samples = [(r.path, r.label, "video") for r in train_pool]
        test_samples = [(r.path, r.label, "video") for r in test_pool]
        print(
            f"[lomo:{resolved_config['name']}] train={len(train_samples)} "
            f"(manipulations={resolved_config['train_manipulations']}) | "
            f"unseen_test={len(test_samples)} (manipulation={test_manipulation})"
        )
        return train_samples, test_samples

    def build_multi_clip_eval_samples(self, records, n_clips=5):
        """T1.6: multi-clip inference sampling. Repeats each record's sample
        n_clips times so DeepFakeDataset's per-call random clip-start sampling
        (mode="sequence", clip_sampling="random") yields n_clips distinct
        clips per video. Returns (samples, video_ids); video_ids[i] identifies
        which source video samples[i] came from (its path is already a stable
        unique identifier) -- group predictions back by video_id and feed the
        resulting {video_id: [clip_score, ...]} to docs/code/metrics.py's
        aggregate_clips()/video_scores_from_clips(). NOTE: pass
        clip_sampling="center" here and every repeat will be the SAME clip --
        use "random" (or a future evenly-spaced sampler, not yet implemented)
        for genuine multi-clip coverage.
        """
        samples = []
        video_ids = []
        for record in records:
            sample = (
                self._record_to_sample(record)
                if isinstance(record, dict)
                else (record["path"], record["label"], record["dtype"])
            )
            for _ in range(max(1, n_clips)):
                samples.append(sample)
                video_ids.append(sample[0])
        return samples, video_ids

    def prepare_records(
        self,
        dtype=None,
        protocol=None,
        dataset_names=None,
        balanced=True,
        train_ratio=DEFAULT_VIDEO_TRAIN_RATIO,
        val_ratio=None,
        split_engine="legacy",
    ):
        self.build()
        resolved_protocol = self._resolve_protocol(dtype=dtype, protocol=protocol)
        filtered_records = self._filter_records(dtype=dtype, dataset_names=dataset_names)

        if val_ratio is None:
            if resolved_protocol in {"video_only", "frame_only"}:
                val_ratio = DEFAULT_VIDEO_VAL_RATIO
            else:
                val_ratio = 0.2

        if split_engine not in {"legacy", "identity_v2"}:
            raise ValueError(f"Unsupported split_engine: {split_engine!r}")

        used_identity_v2 = False
        if split_engine == "identity_v2" and resolved_protocol in {"video_only", "frame_only"}:
            train_records, val_records, test_records = self._prepare_video_identity_v2(
                filtered_records,
                train_ratio=train_ratio,
                val_ratio=val_ratio,
            )
            used_identity_v2 = True
        elif resolved_protocol == "image_only":
            train_records, val_records, test_records = self._prepare_image_only(filtered_records)
        elif resolved_protocol == "video_only":
            train_records, val_records, test_records = self._prepare_video_only(
                filtered_records,
                train_ratio=train_ratio,
                val_ratio=val_ratio,
            )
        elif resolved_protocol == "frame_only":
            train_records, val_records, test_records = self._prepare_frame_only(
                filtered_records,
                train_ratio=train_ratio,
                val_ratio=val_ratio,
            )
        elif resolved_protocol == "combined_aux":
            train_records, val_records, test_records = self._prepare_combined_aux(
                filtered_records,
                train_ratio=train_ratio,
                val_ratio=val_ratio,
            )
        else:
            raise ValueError(f"Unsupported protocol: {resolved_protocol}")

        # identity_v2 already balances via asymmetric clip sampling; applying
        # the legacy oversample-balance on top would double-balance.
        if balanced and not used_identity_v2:
            train_records = self._apply_class_balance(train_records)

        return {
            "protocol": resolved_protocol,
            "split_engine": split_engine if used_identity_v2 else "legacy",
            "train": train_records,
            "val": val_records,
            "test": test_records,
        }
